"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

Détection automatique de l'environnement :
  - VERCEL=1 injecté automatiquement par Vercel → mode production
  - Pas de VERCEL → mode développement local
"""

import os
from pathlib import Path
 
BASE_DIR = Path(__file__).resolve().parent.parent
 
 
# ──────────────────────────────────────────────
# Détection de l'environnement
# ──────────────────────────────────────────────
IS_PRODUCTION = bool(os.environ.get('VERCEL'))   # True sur Vercel, False en local
 
 
# ──────────────────────────────────────────────
# Sécurité
# ──────────────────────────────────────────────
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'dev-secret-key-change-this-in-production'   # utilisé uniquement en local
)
 
DEBUG = not IS_PRODUCTION   # True en local, False sur Vercel
 
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.vercel.app',
    '.now.sh',
]
 
 
# ──────────────────────────────────────────────
# Applications
# ──────────────────────────────────────────────
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'traffic',
]
 
 
# ──────────────────────────────────────────────
# Middleware (whitenoise DOIT être juste après SecurityMiddleware)
# ──────────────────────────────────────────────
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
ROOT_URLCONF = 'config.urls'
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
 
WSGI_APPLICATION = 'config.wsgi.application'
 
 
# ──────────────────────────────────────────────
# Base de données
# SQLite en local, aucune DB sur Vercel (serverless)
# ──────────────────────────────────────────────
if IS_PRODUCTION:
    DATABASES = {}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
 
 
# ──────────────────────────────────────────────
# Internationalisation
# ──────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
 
 
# ──────────────────────────────────────────────
# Fichiers statiques
# ──────────────────────────────────────────────
STATIC_URL  = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
 
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
 
 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'